name: SonarQube Analysis

on:
  push:
    branches:
      - master # You can specify the branch you want to trigger the analysis

jobs:
  sonarqube:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
         with
          java-version:'11'
          distribution:'adopt'

      - name: Build with Maven
        run: mvn clean install -B

      - name: Run SonarQube analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn sonar:sonar -Dsonar.login=$SONAR_TOKEN
