name: SonarQube Analysis

on:
  push:
    branches:
      - master # Set the branch you want to trigger the workflow on

jobs:
  sonarqube:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: 'adopt'# You can specify the Java version you need

    - name: Run SonarQube Scan
      run: |
        /opt/sonar-scanner/sonar-scanner-4.6.2.2472-linux/bin \
        -Dsonar.host.url=http://10.10.30.206:9000 \
        -Dsonar.login=092fdf9ab988219185d967ff9ac5fca696730695 # Replace with your SonarQube token

    - name: Upload SonarQube Analysis
      run: |
        curl -u $SONAR_TOKEN: -X POST \
        "http://10.10.30.206:9000/api/ce/submit?projectKey=myjava&characteristic=branch:master" \
         -H "Content-Type: application/x-www-form-urlencoded"
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      # Add any necessary steps to upload the analysis results to your SonarQube server

