name: SonarQube Analysis

on:
  push:
    branches:
      - master # Adjust this to your main branch name

jobs:
  sonarqube:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 11 # You can specify your desired Java version 
          distribution: 'adopt'
          
      - name: Run SonarQube Scanner
        run: |
          export SONAR_SCANNER_HOME=/opt/sonar-scanner-4.6.2.2472-linux
          $SONAR_SCANNER_HOME/bin/sonar-scanner -Dsonar.login=$SONAR_TOKEN -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.sources=.
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        working-directory: ./ # Set the working directory to the root of the repository






