name: SonarQube Analysis

on:
  push:
    branches:
      - master  # Change this to your main branch

jobs:
  sonarqube:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: SonarQube Scan
      run: |
        /opt/sonar-scanner/sonar-scanner-4.6.2.2472-linux/bin/sonar-scanner \
         -Dsonar.projectKey=myjava\
         -Dsonar.sources=./sample.java  # Set this path to your Java source code
         -Dsonar.host.url=http://10.10.30.206:9000
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}


    - name: Check SonarQube Analysis Status
      run: |
         curl -u $SONAR_TOKEN: -X POST "http://10.10.30.206:9000/api/qualitygates/project_status?projectKey=myjava" -o project_status.json

    - name: Display SonarQube Analysis Status
      run: cat project_status.json

