name: SonarQube Analysis

on:
  push:
    branches:
      - master

jobs:
  sonarqube:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Run SonarScanner
        run: |
          # Set the path to your SonarScanner installation
          SONAR_SCANNER_HOME=/opt/sonar-scanner-4.6.2.2472-linux
          
          # Run SonarScanner analysis
          $SONAR_SCANNER_HOME/bin/sonar-scanner -Dsonar.projectKey=myjava -Dsonar.sources=src -Dsonar.login=092fdf9ab988219185d967ff9ac5fca696730695 -Dsonar.host.url=http://10.10.30.206:9000
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
