name: Find Sonar Scanner Location

on:
  push:
    branches:
      - master # Adjust this to your main branch name

jobs:
  find-scanner-location:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Run find Command for Sonar Scanner
        run: |
          # Use the find command to locate the Sonar Scanner executable
          find / -type f -name sonar-scanner 2>/dev/null
        shell: bash
